### ISSUE TITLE
Error running camel-amq quickstart (2.0.12 & 2.1.5) in OpenShift

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/ipaas-quickstarts#109]
After running the latest karaf camel-amq quikstart using openshift in docker the container fails with the following in the logs..

```
jamesrawlings@jrmacbook:~/fabric8/quickstarts/quickstarts/karaf/camel-amq$ docker logs 6fd1e3e0990b
This is an STI ready Apache Karaf image.
You can use it with the sti tool, to build a docker image out of your source code.

sti build <url to git repo> fabric8/karaf-<version> <target image name>

The git url is expected to host a maven project for karaf, that will generate as part of its output any of the following:

i) One or more kar archives.
ii) A maven repo under fabric8/repository


Running an empty container:
to spin up an empty karaf container with this image you can just:

docker run fabric8/karaf-<version> deploy-and-start

Details:
If a pom.xml is present in the source directory, the project is built with maven and the
output in target will be copied into the /opt/jboss/deploy directory.
```

**Comment by cmoulliard** [comment]
With 2.1.5, no logs are reported by the docker container of `quickstart-karaf-camel-amq` when deployed into the Vagrant VM box (= openshift v.0.5.3) :  

```
docker ps | grep quickstart
dba4f633f560        openshift/origin-pod:v0.5.3               "/pod"                 58 minutes ago      Up 58 minutes                                                                          k8s_POD.78e00c67_quickstart-karaf-camel-amq-controller-yom1z_default_04ea2110-094e-11e5-a8bf-0800275503ae_2db75deb   
docker logs dba4f633f560
$ 
```

**Comment by cmoulliard** [comment]
The `quickstart-karaf-camel-amq` 2.1.5  doesn't work when deployed into the Vagrant VM box (= openshift v.0.5.3) : 

- Openshift screen : orange color (seems not OK)

![screenshot 2015-06-03 08 03 31](https://cloud.githubusercontent.com/assets/463790/7953701/436eec9e-09c8-11e5-8067-356cef5a5dd2.png)

- Fabric8 screen : everything looks good

![screenshot 2015-06-03 08 03 16](https://cloud.githubusercontent.com/assets/463790/7953704/474a24be-09c8-11e5-9b7b-d7091a8ebb16.png)


- Quickstart screen : error reported

![screenshot 2015-06-03 08 03 50](https://cloud.githubusercontent.com/assets/463790/7953681/04bad436-09c8-11e5-9790-05a5d4a6769f.png)

**Comment by jstrachan** [comment]
I'm not sure the karaf quickstarts are working right now.

Ideally we'd port them to use the karaf maven plugin to create static karaf images that startup fast; without relying on a more complex pom.xml configuration to make kars, like this example using mvn dependencies on features/bundles:
https://github.com/apache/karaf/blob/master/assemblies/apache-karaf-minimal/pom.xml#L97

then we'd create a standard karaf based assembly for use in the docker maven plugin to minimise the changes required to a pom.xml for it to use a karaf assembly & docker.

FWIW I've raised this to get the mvn stuff figured out: https://github.com/fabric8io/fabric8/issues/4075

**Comment by davsclaus** [comment]
Okat the camel-amq quickstart works better now - the karaf image startup and if you install the fabric8mq app first, then it has a service to connect to.

But it fails in AMQ with this error
```
2015-06-16 13:10:22,263 | INFO  | pool-7-thread-1  | MQs                              | 90 - io.fabric8.mq.client - 2.1.11 | Connecting to ActiveMQ broker on 172.30.25.196:6163 from $FABRIC8MQ_SERVICE_HOST and $FABRIC8MQ_SERVICE_PORT. To use a different broker service please specify $FABRIC8MQ_SERVICE_NAME=someBrokerServiceName where 'someBrokerServiceName' is a defined ActiveMQ broker service in Kubernetes
2015-06-16 13:10:22,263 | INFO  | pool-7-thread-1  | MQs                              | 90 - io.fabric8.mq.client - 2.1.11 | BrokerURL is: failover:(tcp://172.30.25.196:6163)
2015-06-16 13:10:22,309 | INFO  | pool-7-thread-1  | XPathBuilder                     | 69 - org.apache.camel.camel-core - 2.15.2 | Created default XPathFactory com.sun.org.apache.xpath.internal.jaxp.XPathFactoryImpl@4c59cdaa
2015-06-16 13:10:22,376 | INFO  | pool-7-thread-1  | BlueprintCamelContext            | 69 - org.apache.camel.camel-core - 2.15.2 | Route: file-to-jms-route started and consuming from: Endpoint[file://work/jms/input]
2015-06-16 13:10:22,624 | INFO  | ActiveMQ Task-1  | FailoverTransport                | 87 - org.apache.activemq.activemq-osgi - 5.11.1 | Successfully connected to tcp://172.30.25.196:6163
2015-06-16 13:10:22,657 | WARN  | pool-7-thread-1  | FailoverTransport                | 87 - org.apache.activemq.activemq-osgi - 5.11.1 | Transport (tcp:///172.30.25.196:6163@33084) failed, attempting to automatically reconnect
org.apache.activemq.transport.InactivityIOException: Cannot send, channel has already failed: tcp://172.30.25.196:6163
	at org.apache.activemq.transport.AbstractInactivityMonitor.doOnewaySend(AbstractInactivityMonitor.java:297)
	at org.apache.activemq.transport.AbstractInactivityMonitor.oneway(AbstractInactivityMonitor.java:286)
	at org.apache.activemq.transport.TransportFilter.oneway(TransportFilter.java:85)
	at org.apache.activemq.transport.WireFormatNegotiator.oneway(WireFormatNegotiator.java:104)
	at org.apache.activemq.transport.failover.FailoverTransport.oneway(FailoverTransport.java:665)
	at org.apache.activemq.transport.MutexTransport.oneway(MutexTransport.java:68)
	at org.apache.activemq.transport.ResponseCorrelator.asyncRequest(ResponseCorrelator.java:81)
	at org.apache.activemq.transport.ResponseCorrelator.request(ResponseCorrelator.java:86)
	at org.apache.activemq.ActiveMQConnection.syncSendPacket(ActiveMQConnection.java:1409)
	at org.apache.activemq.ActiveMQConnection.ensureConnectionInfoSent(ActiveMQConnection.java:1521)
	at org.apache.activemq.ActiveMQConnection.start(ActiveMQConnection.java:528)
	at org.apache.activemq.jms.pool.ConnectionPool.start(ConnectionPool.java:117)
	at org.apache.activemq.jms.pool.PooledConnection.start(PooledConnection.java:95)
	at org.springframework.jms.listener.AbstractJmsListeningContainer.startSharedConnection(AbstractJmsListeningContainer.java:442)
	at org.springframework.jms.listener.DefaultMessageListenerContainer.startSharedConnection(DefaultMessageListenerContainer.java:784)
	at org.springframework.jms.listener.AbstractJmsListeningContainer.doStart(AbstractJmsListeningContainer.java:292)
	at org.springframework.jms.listener.AbstractJmsListeningContainer.start(AbstractJmsListeningContainer.java:265)
	at org.springframework.jms.listener.DefaultMessageListenerContainer.start(DefaultMessageListenerContainer.java:566)
	at org.apache.camel.component.jms.JmsConsumer.startListenerContainer(JmsConsumer.java:105)
	at org.apache.camel.component.jms.JmsConsumer.prepareAndStartListenerContainer(JmsConsumer.java:171)
	at org.apache.camel.component.jms.JmsConsumer.doStart(JmsConsumer.java:155)
	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
	at org.apache.camel.impl.DefaultCamelContext.startService(DefaultCamelContext.java:2869)[69:org.apache.camel.camel-core:2.15.2]
	at org.apache.camel.impl.DefaultCamelContext.doStartOrResumeRouteConsumers(DefaultCamelContext.java:3163)[69:org.apache.camel.camel-core:2.15.2]
	at org.apache.camel.impl.DefaultCamelContext.doStartRouteConsumers(DefaultCamelContext.java:3099)[69:org.apache.camel.camel-core:2.15.2]
	at org.apache.camel.impl.DefaultCamelContext.safelyStartRouteServices(DefaultCamelContext.java:3029)[69:org.apache.camel.camel-core:2.15.2]
	at org.apache.camel.impl.DefaultCamelContext.doStartOrResumeRoutes(DefaultCamelContext.java:2797)[69:org.apache.camel.camel-core:2.15.2]
	at org.apache.camel.impl.DefaultCamelContext.doStartCamel(DefaultCamelContext.java:2653)[69:org.apache.camel.camel-core:2.15.2]
	at org.apache.camel.impl.DefaultCamelContext.access$000(DefaultCamelContext.java:167)[69:org.apache.camel.camel-core:2.15.2]
	at org.apache.camel.impl.DefaultCamelContext$2.call(DefaultCamelContext.java:2467)
	at org.apache.camel.impl.DefaultCamelContext$2.call(DefaultCamelContext.java:2463)
	at org.apache.camel.impl.DefaultCamelContext.doWithDefinedClassLoader(DefaultCamelContext.java:2486)[69:org.apache.camel.camel-core:2.15.2]
	at org.apache.camel.impl.DefaultCamelContext.doStart(DefaultCamelContext.java:2463)[69:org.apache.camel.camel-core:2.15.2]
	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
	at org.apache.camel.impl.DefaultCamelContext.start(DefaultCamelContext.java:2432)[69:org.apache.camel.camel-core:2.15.2]
	at org.apache.camel.blueprint.BlueprintCamelContext.start(BlueprintCamelContext.java:180)
	at org.apache.camel.blueprint.BlueprintCamelContext.maybeStart(BlueprintCamelContext.java:212)
	at org.apache.camel.blueprint.BlueprintCamelContext.serviceChanged(BlueprintCamelContext.java:150)
	at org.apache.felix.framework.util.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:943)[org.apache.felix.framework-4.4.1.jar:]
	at org.apache.felix.framework.util.EventDispatcher.fireEventImmediately(EventDispatcher.java:794)[org.apache.felix.framework-4.4.1.jar:]
	at org.apache.felix.framework.util.EventDispatcher.fireServiceEvent(EventDispatcher.java:544)[org.apache.felix.framework-4.4.1.jar:]
	at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4445)[org.apache.felix.framework-4.4.1.jar:]
	at org.apache.felix.framework.Felix.registerService(Felix.java:3431)[org.apache.felix.framework-4.4.1.jar:]
	at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:346)
	at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:353)
	at org.apache.camel.blueprint.BlueprintCamelContext.init(BlueprintCamelContext.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[:1.7.0_65]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)[:1.7.0_65]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[:1.7.0_65]
	at java.lang.reflect.Method.invoke(Method.java:606)[:1.7.0_65]
	at org.apache.aries.blueprint.utils.ReflectionUtils.invoke(ReflectionUtils.java:297)[14:org.apache.aries.blueprint.core:1.4.3]
	at org.apache.aries.blueprint.container.BeanRecipe.invoke(BeanRecipe.java:958)[14:org.apache.aries.blueprint.core:1.4.3]
	at org.apache.aries.blueprint.container.BeanRecipe.runBeanProcInit(BeanRecipe.java:712)[14:org.apache.aries.blueprint.core:1.4.3]
	at org.apache.aries.blueprint.container.BeanRecipe.internalCreate2(BeanRecipe.java:824)[14:org.apache.aries.blueprint.core:1.4.3]
	at org.apache.aries.blueprint.container.BeanRecipe.internalCreate(BeanRecipe.java:787)[14:org.apache.aries.blueprint.core:1.4.3]
	at org.apache.aries.blueprint.di.AbstractRecipe$1.call(AbstractRecipe.java:79)[14:org.apache.aries.blueprint.core:1.4.3]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)[:1.7.0_65]
	at org.apache.aries.blueprint.di.AbstractRecipe.create(AbstractRecipe.java:88)[14:org.apache.aries.blueprint.core:1.4.3]
	at org.apache.aries.blueprint.container.BlueprintRepository.createInstances(BlueprintRepository.java:245)[14:org.apache.aries.blueprint.core:1.4.3]
	at org.apache.aries.blueprint.container.BlueprintRepository.createAll(BlueprintRepository.java:183)[14:org.apache.aries.blueprint.core:1.4.3]
	at org.apache.aries.blueprint.container.BlueprintContainerImpl.instantiateEagerComponents(BlueprintContainerImpl.java:682)[14:org.apache.aries.blueprint.core:1.4.3]
	at org.apache.aries.blueprint.container.BlueprintContainerImpl.doRun(BlueprintContainerImpl.java:377)[14:org.apache.aries.blueprint.core:1.4.3]
	at org.apache.aries.blueprint.container.BlueprintContainerImpl.run(BlueprintContainerImpl.java:269)[14:org.apache.aries.blueprint.core:1.4.3]
	at org.apache.aries.blueprint.container.BlueprintExtender.createContainer(BlueprintExtender.java:294)[14:org.apache.aries.blueprint.core:1.4.3]
	at org.apache.aries.blueprint.container.BlueprintExtender.createContainer(BlueprintExtender.java:263)[14:org.apache.aries.blueprint.core:1.4.3]
	at org.apache.aries.blueprint.container.BlueprintExtender.modifiedBundle(BlueprintExtender.java:253)[14:org.apache.aries.blueprint.core:1.4.3]
	at org.apache.aries.util.tracker.hook.BundleHookBundleTracker$Tracked.customizerModified(BundleHookBundleTracker.java:500)[9:org.apache.aries.util:1.1.0]
	at org.apache.aries.util.tracker.hook.BundleHookBundleTracker$Tracked.customizerModified(BundleHookBundleTracker.java:433)[9:org.apache.aries.util:1.1.0]
	at org.apache.aries.util.tracker.hook.BundleHookBundleTracker$AbstractTracked.track(BundleHookBundleTracker.java:725)[9:org.apache.aries.util:1.1.0]
	at org.apache.aries.util.tracker.hook.BundleHookBundleTracker$Tracked.bundleChanged(BundleHookBundleTracker.java:463)[9:org.apache.aries.util:1.1.0]
	at org.apache.aries.util.tracker.hook.BundleHookBundleTracker$BundleEventHook.event(BundleHookBundleTracker.java:422)[9:org.apache.aries.util:1.1.0]
	at org.apache.felix.framework.util.SecureAction.invokeBundleEventHook(SecureAction.java:1127)[org.apache.felix.framework-4.4.1.jar:]
	at org.apache.felix.framework.util.EventDispatcher.createWhitelistFromHooks(EventDispatcher.java:696)[org.apache.felix.framework-4.4.1.jar:]
	at org.apache.felix.framework.util.EventDispatcher.fireBundleEvent(EventDispatcher.java:484)[org.apache.felix.framework-4.4.1.jar:]
	at org.apache.felix.framework.Felix.fireBundleEvent(Felix.java:4429)[org.apache.felix.framework-4.4.1.jar:]
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2100)[org.apache.felix.framework-4.4.1.jar:]
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:976)[org.apache.felix.framework-4.4.1.jar:]
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:963)[org.apache.felix.framework-4.4.1.jar:]
	at org.apache.karaf.features.internal.FeaturesServiceImpl.doInstallFeatures(FeaturesServiceImpl.java:575)[7:org.apache.karaf.features.core:2.4.2]
	at org.apache.karaf.features.internal.FeaturesServiceImpl$1.call(FeaturesServiceImpl.java:461)[7:org.apache.karaf.features.core:2.4.2]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)[:1.7.0_65]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)[:1.7.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)[:1.7.0_65]
	at java.lang.Thread.run(Thread.java:745)[:1.7.0_65]
2015-06-16 13:10:38,089 | WARN  | ActiveMQ Task-2  | FailoverTransport                | 87 - org.apache.activemq.activemq-osgi - 5.11.1 | Failed to connect to [tcp://172.30.25.196:6163] after: 10 attempt(s) continuing to retry.
[root@quickstart-karaf-camel-amq-v32vz log]#
```

@rajdavies maybe this rings a bell?

**Comment by davsclaus** [comment]
It seems the service is correct
```
davsclaus:~/workspace/quickstarts/quickstarts/karaf (482)/$ osc get services
NAME              LABELS                                                 SELECTOR                                               IP(S)            PORT(S)
docker-registry   docker-registry=default                                docker-registry=default                                172.30.111.183   5000/TCP
fabric8           component=console,provider=fabric8                     component=console,provider=fabric8                     172.30.248.185   80/TCP
fabric8mq         component=fabric8MQ,group=fabric8mq,provider=fabric8   component=fabric8MQ,group=fabric8mq,provider=fabric8   172.30.25.196    6163/TCP
```

**Comment by davsclaus** [comment]
mq stuff removed
