### ISSUE TITLE
 Application startup failed in container with image built from quickstart/spring-boot/camel

### ISSUE THREAD

**Issue by xiazhao2015** [fabric8io/ipaas-quickstarts#1105]
OSE/Mgmt Console
M
M

Version-Release number of selected component (if applicable):
oc v3.1.1.5
kubernetes v1.1.0-origin-1107-g4c8e6f4
Firefox 43.0.4
Apache Maven 3.2.2
Java version: 1.8.0_65

Steps to Reproduce:

1. Deploy the application on OSE from https://github.com/fabric8io/ipaas-quickstarts/tree/redhat/quickstart/spring-boot/camel
2. Look at the application pod status

Actual Result:
Application pod is CrashLoopBackOff because failed to start up

Expected Result:
Application should be able to start up

Additional info:
full logs:

oc logs springboot-camel-2-5gwjt
I> No access restrictor found, access to all MBean is allowed
Jolokia: Agent started with URL http://10.1.1.176:8778/jolokia/

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.3.0.RELEASE)

2016-01-19 10:21:11.640  INFO 1 --- [           main] o.apache.camel.spring.boot.FatJarRouter  : Starting FatJarRouter v2.16.1 on springboot-camel-2-5gwjt with PID 1 (started by ? in /app)
2016-01-19 10:21:11.645  INFO 1 --- [           main] o.apache.camel.spring.boot.FatJarRouter  : No profiles are active
2016-01-19 10:21:11.827  INFO 1 --- [           main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@2bd8ba4f: startup date [Tue Jan 19 10:21:11 UTC 2016]; root of context hierarchy
2016-01-19 10:21:14.369  INFO 1 --- [           main] f.a.AutowiredAnnotationBeanPostProcessor : JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2016-01-19 10:21:14.408  WARN 1 --- [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor': Invocation of init method failed; nested exception is javax.validation.ValidationException: Unable to create a Configuration, because no Bean Validation provider could be found. Add a provider like Hibernate Validator (RI) to your classpath.
2016-01-19 10:21:14.413  INFO 1 --- [           main] .b.l.ClasspathLoggingApplicationListener : Application failed to start with classpath: [jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/camel-core-2.16.1.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/slf4j-api-1.7.13.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/jaxb-core-2.2.11.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/jaxb-impl-2.2.11.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/camel-spring-boot-2.16.1.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/camel-spring-2.16.1.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/spring-context-4.2.3.RELEASE.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/spring-beans-4.2.3.RELEASE.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/spring-expression-4.2.3.RELEASE.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/spring-aop-4.2.3.RELEASE.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/aopalliance-1.0.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/spring-tx-4.2.3.RELEASE.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/camel-metrics-2.16.1.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/metrics-core-3.1.2.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/metrics-json-3.1.2.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/jackson-databind-2.6.3.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/jackson-annotations-2.6.3.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/jackson-core-2.6.3.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/spring-boot-starter-1.3.0.RELEASE.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/spring-boot-1.3.0.RELEASE.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/spring-boot-autoconfigure-1.3.0.RELEASE.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/spring-boot-starter-logging-1.3.0.RELEASE.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/logback-classic-1.1.3.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/logback-core-1.1.3.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/jcl-over-slf4j-1.7.13.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/jul-to-slf4j-1.7.13.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/log4j-over-slf4j-1.7.13.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/spring-core-4.2.3.RELEASE.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/snakeyaml-1.16.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/arquillian-junit-core-1.1.10.Final.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/arquillian-test-api-1.1.10.Final.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/arquillian-core-api-1.1.10.Final.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/arquillian-test-spi-1.1.10.Final.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/arquillian-core-spi-1.1.10.Final.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/arquillian-container-test-api-1.1.10.Final.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/shrinkwrap-api-1.2.2.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/arquillian-container-test-spi-1.1.10.Final.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/arquillian-core-impl-base-1.1.10.Final.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/arquillian-test-impl-base-1.1.10.Final.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/arquillian-container-impl-base-1.1.10.Final.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/arquillian-config-api-1.1.10.Final.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/arquillian-config-impl-base-1.1.10.Final.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/shrinkwrap-descriptors-spi-2.0.0-alpha-8.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/arquillian-container-test-impl-base-1.1.10.Final.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/shrinkwrap-impl-base-1.2.2.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/shrinkwrap-spi-1.2.2.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/fabric8-annotations-2.2.88.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/javax.inject-1.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/kubernetes-api-2.2.88.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/validation-api-1.1.0.Final.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/jackson-dataformat-yaml-2.6.3.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/json-20140107.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/dnsjava-2.1.7.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/openshift-client-1.3.66.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/kubernetes-client-1.3.66.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/kubernetes-model-1.0.40.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/jackson-module-jaxb-annotations-2.6.3.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/okhttp-2.7.0.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/okio-1.6.0.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/logging-interceptor-2.7.0.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/okhttp-ws-2.7.0.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/kubernetes-client-1.3.66-tests.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/assertj-core-1.7.0.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/jolokia-assertions-2.2.88.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/jolokia-client-java-1.3.2.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/json-simple-1.1.1.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/httpclient-osgi-4.3.3.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/commons-codec-1.10.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/commons-logging-1.2.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/kubernetes-jolokia-2.2.88.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/fabric8-utils-2.2.88.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/fabric8-devops-2.2.88.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/pax-url-aether-2.4.5.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/arquillian-container-spi-1.1.10.Final.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/shrinkwrap-descriptors-api-base-2.0.0-alpha-8.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/shrinkwrap-resolver-api-2.2.1.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/shrinkwrap-resolver-spi-2.2.1.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/shrinkwrap-resolver-api-maven-2.2.1.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/shrinkwrap-resolver-spi-maven-2.2.1.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/shrinkwrap-resolver-api-maven-archive-2.2.1.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/shrinkwrap-resolver-impl-maven-2.2.1.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/aether-api-1.0.0.v20140518.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/aether-impl-1.0.0.v20140518.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/aether-spi-1.0.0.v20140518.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/aether-util-1.0.0.v20140518.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/aether-connector-basic-1.0.0.v20140518.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/aether-transport-wagon-1.0.0.v20140518.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/maven-aether-provider-3.2.5.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/maven-model-3.2.5.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/maven-model-builder-3.2.5.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/plexus-component-annotations-1.5.5.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/maven-repository-metadata-3.2.5.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/maven-settings-3.2.5.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/maven-settings-builder-3.2.5.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/guava-18.0.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/plexus-interpolation-1.21.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/plexus-sec-dispatcher-1.3.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/plexus-cipher-1.4.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/wagon-provider-api-2.6.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/wagon-file-2.6.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/commons-lang-2.6.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/wagon-http-lightweight-2.6.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/wagon-http-shared-2.6.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/jsoup-1.7.2.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/commons-io-2.4.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/shrinkwrap-resolver-impl-maven-archive-2.2.1.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/shrinkwrap-resolver-spi-maven-archive-2.2.1.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/org.eclipse.sisu.plexus-0.3.0.M1.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/cdi-api-1.2.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/javax.el-api-2.2.5.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/javax.interceptor-api-1.2.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/org.eclipse.sisu.inject-0.3.0.M1.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/plexus-compiler-javac-2.3.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/plexus-compiler-api-2.3.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/plexus-utils-3.0.22.jar!/, jar:file:/app/springboot-camel-2.2.94-SNAPSHOT.jar!/lib/xml-apis-1.4.01.jar!/]
2016-01-19 10:21:14.421 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor': Invocation of init method failed; nested exception is javax.validation.ValidationException: Unable to create a Configuration, because no Bean Validation provider could be found. Add a provider like Hibernate Validator (RI) to your classpath.
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1578) ~[spring-beans-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545) ~[spring-beans-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) ~[spring-beans-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:207) ~[spring-context-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:686) ~[spring-context-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:522) ~[spring-context-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752) ~[spring-boot-1.3.0.RELEASE.jar!/:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:347) ~[spring-boot-1.3.0.RELEASE.jar!/:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:295) ~[spring-boot-1.3.0.RELEASE.jar!/:1.3.0.RELEASE]
	at org.apache.camel.spring.boot.FatJarRouter.main(FatJarRouter.java:26) [camel-spring-boot-2.16.1.jar!/:2.16.1]
	at io.fabric8.quickstarts.camel.MyCamelRoute.main(MyCamelRoute.java:29) [springboot-camel-2.2.94-SNAPSHOT.jar!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_51]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53) [springboot-camel-2.2.94-SNAPSHOT.jar!/:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]
Caused by: javax.validation.ValidationException: Unable to create a Configuration, because no Bean Validation provider could be found. Add a provider like Hibernate Validator (RI) to your classpath.
	at javax.validation.Validation$GenericBootstrapImpl.configure(Validation.java:271) ~[validation-api-1.1.0.Final.jar!/:na]
	at org.springframework.validation.beanvalidation.LocalValidatorFactoryBean.afterPropertiesSet(LocalValidatorFactoryBean.java:223) ~[spring-context-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
	at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor$Jsr303ValidatorFactory.run(ConfigurationPropertiesBindingPostProcessor.java:401) ~[spring-boot-1.3.0.RELEASE.jar!/:1.3.0.RELEASE]
	at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.afterPropertiesSet(ConfigurationPropertiesBindingPostProcessor.java:199) ~[spring-boot-1.3.0.RELEASE.jar!/:1.3.0.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637) ~[spring-beans-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574) ~[spring-beans-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
	... 20 common frames omitted

java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor': Invocation of init method failed; nested exception is javax.validation.ValidationException: Unable to create a Configuration, because no Bean Validation provider could be found. Add a provider like Hibernate Validator (RI) to your classpath.
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1578)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:207)
	at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:686)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:522)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752)
	at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:347)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:295)
	at org.apache.camel.spring.boot.FatJarRouter.main(FatJarRouter.java:26)
	at io.fabric8.quickstarts.camel.MyCamelRoute.main(MyCamelRoute.java:29)
	... 6 more
Caused by: javax.validation.ValidationException: Unable to create a Configuration, because no Bean Validation provider could be found. Add a provider like Hibernate Validator (RI) to your classpath.
	at javax.validation.Validation$GenericBootstrapImpl.configure(Validation.java:271)
	at org.springframework.validation.beanvalidation.LocalValidatorFactoryBean.afterPropertiesSet(LocalValidatorFactoryBean.java:223)
	at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor$Jsr303ValidatorFactory.run(ConfigurationPropertiesBindingPostProcessor.java:401)
	at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.afterPropertiesSet(ConfigurationPropertiesBindingPostProcessor.java:199)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574)
	... 20 more

**Comment by xiazhao2015** [comment]
Issue reproducible with latest code springboot-camel:2.2.98-SNAPSHOT

**Comment by arpitshah1** [comment]
Added dependency and it worked 

<dependency>
<groupId>org.hibernate</groupId>
<artifactId>hibernate-validator</artifactId>
</dependency>

**Comment by davsclaus** [comment]
Yeah thanks for reporting we fixed that recently

**Comment by sugarbyheart** [comment]
@arpitshah1  I have the same problem with using fabric api version 1.1.0.CR5, and the method works for me. Could u have the root cause?
