### ISSUE TITLE
CXF CDI Pod reports a java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.ObjectMapper

### ISSUE THREAD

**Issue by cmoulliard** [fabric8io/ipaas-quickstarts#1227]
This error is reported within the log of CXF CDI Quickstart deployed as a pod 

````
[root@vagrant vagrant]# oc logs demo1-uy23s
Executing /deployments/bin/run ...
Launching application in folder: /deployments
Running  java  -javaagent:/opt/jolokia/jolokia.jar=config=/opt/jolokia/jolokia.properties,useSslClientAuthentication=true,extraClientCheck=true,protocol=https,caCert=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt,clientPrincipal=cn=system:master-proxy -classpath :/deployments/lib/demo1.jar:/deployments/lib/fabric8-cxf-2.2.114.jar:/deployments/lib/org.osgi.core-4.3.1.jar:/deployments/lib/org.osgi.compendium-4.3.1.jar:/deployments/lib/fabric8-utils-2.2.114.jar:/deployments/lib/jackson-core-2.6.4.jar:/deployments/lib/cxf-core-3.1.4.jar:/deployments/lib/woodstox-core-asl-4.4.1.jar:/deployments/lib/stax2-api-3.1.4.jar:/deployments/lib/xmlschema-core-2.2.1.jar:/deployments/lib/cxf-rt-frontend-jaxws-3.1.4.jar:/deployments/lib/xml-resolver-1.2.jar:/deployments/lib/asm-5.0.4.jar:/deployments/lib/cxf-rt-bindings-soap-3.1.4.jar:/deployments/lib/cxf-rt-wsdl-3.1.4.jar:/deployments/lib/cxf-rt-databinding-jaxb-3.1.4.jar:/deployments/lib/jaxb-impl-2.2.11.jar:/deployments/lib/jaxb-core-2.2.11.jar:/deployments/lib/cxf-rt-bindings-xml-3.1.4.jar:/deployments/lib/cxf-rt-frontend-simple-3.1.4.jar:/deployments/lib/cxf-rt-ws-addr-3.1.4.jar:/deployments/lib/cxf-rt-rs-client-3.1.4.jar:/deployments/lib/cxf-rt-ws-policy-3.1.4.jar:/deployments/lib/wsdl4j-1.6.3.jar:/deployments/lib/neethi-3.0.3.jar:/deployments/lib/cxf-rt-transports-local-3.1.4.jar:/deployments/lib/cxf-rt-transports-http-jetty-3.1.4.jar:/deployments/lib/jetty-continuation-9.2.11.v20150529.jar:/deployments/lib/cxf-rt-rs-service-description-3.1.4.jar:/deployments/lib/cxf-integration-cdi-3.1.4.jar:/deployments/lib/cxf-rt-frontend-jaxrs-3.1.4.jar:/deployments/lib/javax.ws.rs-api-2.0.1.jar:/deployments/lib/javax.annotation-api-1.2.jar:/deployments/lib/cxf-rt-transports-http-3.1.4.jar:/deployments/lib/cxf-rt-management-3.1.4.jar:/deployments/lib/weld-se-2.3.3.Final.jar:/deployments/lib/weld-core-2.3.3.Final.jar:/deployments/lib/weld-api-2.3.SP2.jar:/deployments/lib/weld-spi-2.3.SP2.jar:/deployments/lib/jboss-classfilewriter-1.1.2.Final.jar:/deployments/lib/jboss-annotations-api_1.2_spec-1.0.0.Final.jar:/deployments/lib/guava-18.0.jar:/deployments/lib/jboss-el-api_3.0_spec-1.0.0.Alpha1.jar:/deployments/lib/jboss-interceptors-api_1.2_spec-1.0.0.Final.jar:/deployments/lib/jboss-logging-3.2.1.Final.jar:/deployments/lib/weld-servlet-2.3.3.Final.jar:/deployments/lib/deltaspike-cdictrl-weld-1.5.4.jar:/deployments/lib/deltaspike-cdictrl-api-1.5.4.jar:/deployments/lib/jetty-server-9.2.10.v20150310.jar:/deployments/lib/javax.servlet-api-3.0.1.jar:/deployments/lib/jetty-servlet-9.2.10.v20150310.jar:/deployments/lib/jetty-servlets-9.2.10.v20150310.jar:/deployments/lib/jetty-jndi-9.2.10.v20150310.jar:/deployments/lib/jetty-jsp-9.2.10.v20150310.jar:/deployments/lib/jetty-schemas-3.1.M0.jar:/deployments/lib/javax.servlet.jsp-api-2.3.1.jar:/deployments/lib/javax.servlet.jsp-2.3.2.jar:/deployments/lib/javax.servlet.jsp.jstl-1.2.0.v201105211821.jar:/deployments/lib/javax.servlet.jsp.jstl-1.2.2.jar:/deployments/lib/javax.el-3.0.0.jar:/deployments/lib/org.eclipse.jdt.core-3.8.2.v20130121.jar:/deployments/lib/jetty-http-9.2.10.v20150310.jar:/deployments/lib/jetty-io-9.2.10.v20150310.jar:/deployments/lib/jetty-util-9.2.10.v20150310.jar:/deployments/lib/jetty-security-9.2.10.v20150310.jar:/deployments/lib/swagger-jaxrs-1.5.7.jar:/deployments/lib/jackson-dataformat-yaml-2.4.5.jar:/deployments/lib/snakeyaml-1.12.jar:/deployments/lib/jackson-dataformat-xml-2.4.5.jar:/deployments/lib/jackson-module-jaxb-annotations-2.4.5.jar:/deployments/lib/swagger-core-1.5.7.jar:/deployments/lib/commons-lang3-3.2.1.jar:/deployments/lib/jackson-annotations-2.4.5.jar:/deployments/lib/jackson-datatype-joda-2.4.5.jar:/deployments/lib/joda-time-2.2.jar:/deployments/lib/swagger-models-1.5.7.jar:/deployments/lib/swagger-annotations-1.5.7.jar:/deployments/lib/validation-api-1.1.0.Final.jar:/deployments/lib/reflections-0.9.10.jar:/deployments/lib/javassist-3.19.0-GA.jar:/deployments/lib/annotations-2.0.1.jar:/deployments/lib/jackson-jaxrs-json-provider-2.4.5.jar:/deployments/lib/jackson-jaxrs-base-2.4.5.jar:/deployments/lib/slf4j-api-1.7.12.jar org.example.ApplicationStarter
I> No access restrictor found, access to all MBean is allowed
Jolokia: Agent started with URL https://172.17.0.14:8778/jolokia/
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Starting REST server at:         http://localhost:9092/
View the services at:            http://localhost:9092//servicesList
View an example REST service at: http://localhost:9092/cxfcdi/customerservice/customers/123

May 12, 2016 11:44:14 AM org.jboss.weld.environment.servlet.Listener contextInitialized
INFO: WELD-ENV-001007: Initialize Weld using ServletContextListener
May 12, 2016 11:44:14 AM org.jboss.weld.bootstrap.WeldStartup <clinit>
INFO: WELD-000900: 2.3.3 (Final)
May 12, 2016 11:44:15 AM org.jboss.weld.bootstrap.WeldStartup startContainer
INFO: WELD-000101: Transactional services not available. Injection of @Inject UserTransaction not available. Transactional observers will be invoked synchronously.
May 12, 2016 11:44:15 AM org.jboss.weld.environment.jetty.JettyContainer initialize
INFO: WELD-ENV-001201: Jetty 7.2+ detected, CDI injection will be available in Servlets and Filters. Injection into Listeners is not supported.
Exception in thread "main" java.lang.TypeNotPresentException: Type com.fasterxml.jackson.databind.ObjectMapper not present
	at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:117)
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125)
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Reifier.java:68)
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:138)
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at sun.reflect.generics.repository.ClassRepository.getSuperclass(ClassRepository.java:87)
	at java.lang.Class.getGenericSuperclass(Class.java:777)
	at org.jboss.weld.util.reflection.HierarchyDiscovery.discoverFromClass(HierarchyDiscovery.java:137)
	at org.jboss.weld.util.reflection.HierarchyDiscovery.discoverTypes(HierarchyDiscovery.java:111)
	at org.jboss.weld.util.reflection.HierarchyDiscovery.<init>(HierarchyDiscovery.java:93)
	at org.jboss.weld.util.reflection.HierarchyDiscovery.<init>(HierarchyDiscovery.java:86)
	at org.jboss.weld.annotated.enhanced.TypeClosureLazyValueHolder.computeValue(TypeClosureLazyValueHolder.java:43)
	at org.jboss.weld.annotated.enhanced.TypeClosureLazyValueHolder.computeValue(TypeClosureLazyValueHolder.java:33)
	at org.jboss.weld.util.LazyValueHolder.get(LazyValueHolder.java:35)
	at org.jboss.weld.annotated.slim.backed.BackedAnnotated.getTypeClosure(BackedAnnotated.java:27)
	at org.jboss.weld.annotated.enhanced.jlr.AbstractEnhancedAnnotated.getTypeClosure(AbstractEnhancedAnnotated.java:200)
	at org.jboss.weld.util.Beans.getTypes(Beans.java:442)
	at org.jboss.weld.bean.attributes.BeanAttributesFactory$BeanAttributesBuilder.<init>(BeanAttributesFactory.java:113)
	at org.jboss.weld.bean.attributes.BeanAttributesFactory$BeanAttributesBuilder.<init>(BeanAttributesFactory.java:93)
	at org.jboss.weld.bean.attributes.BeanAttributesFactory.forBean(BeanAttributesFactory.java:70)
	at org.jboss.weld.bootstrap.AbstractBeanDeployer.createProducerField(AbstractBeanDeployer.java:222)
	at org.jboss.weld.bootstrap.AbstractBeanDeployer.createProducerFields(AbstractBeanDeployer.java:242)
	at org.jboss.weld.bootstrap.AbstractBeanDeployer.createObserversProducersDisposers(AbstractBeanDeployer.java:177)
	at org.jboss.weld.bootstrap.ConcurrentBeanDeployer$4.doWork(ConcurrentBeanDeployer.java:106)
	at org.jboss.weld.bootstrap.ConcurrentBeanDeployer$4.doWork(ConcurrentBeanDeployer.java:103)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:63)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.ObjectMapper
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:114)
	... 31 more
````

Version used : fabric8-cxf-2.2.114

**Comment by cmoulliard** [comment]
Fixed : https://github.com/fabric8io/ipaas-quickstarts/pull/1228
