### ISSUE TITLE
java.lang.NoClassDefFoundError: com/fasterxml/jackson/dataformat/yaml/YAMLFactory - Swagger

### ISSUE THREAD

**Issue by cmoulliard** [fabric8io/ipaas-quickstarts#1251]
This error is reported when we deploy CXF CDI Quickstart (2.2.125) as pod 

```
Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/dataformat/yaml/YAMLFactory
	at io.swagger.util.Json.mapper(Json.java:13)
	at io.swagger.converter.ModelConverters.<init>(ModelConverters.java:31)
	at io.swagger.converter.ModelConverters.<clinit>(ModelConverters.java:23)
	at io.swagger.jaxrs.Reader.parseMethod(Reader.java:788)
	at io.swagger.jaxrs.Reader.read(Reader.java:295)
	at io.swagger.jaxrs.Reader.read(Reader.java:147)
	at io.swagger.jaxrs.config.BeanConfig.scanAndRead(BeanConfig.java:223)
	at io.swagger.jaxrs.config.BeanConfig.setScan(BeanConfig.java:204)
	at org.apache.cxf.jaxrs.swagger.Swagger2Feature.addSwaggerResource(Swagger2Feature.java:109)
	at org.apache.cxf.jaxrs.swagger.AbstractSwaggerFeature.initialize(AbstractSwaggerFeature.java:46)
	at org.apache.cxf.jaxrs.JAXRSServerFactoryBean.applyFeatures(JAXRSServerFactoryBean.java:252)
	at org.apache.cxf.jaxrs.JAXRSServerFactoryBean.create(JAXRSServerFactoryBean.java:196)
	at org.apache.cxf.jaxrs.JAXRSServerFactoryBean.init(JAXRSServerFactoryBean.java:142)
	at org.apache.cxf.cdi.JAXRSCdiResourceExtension.load(JAXRSCdiResourceExtension.java:103)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:88)
	... 30 more
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.dataformat.yaml.YAMLFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 49 more

	at org.jboss.weld.bootstrap.events.AbstractDeploymentContainerEvent.fire(AbstractDeploymentContainerEvent.java:37)
	at org.jboss.weld.bootstrap.events.AfterDeploymentValidationImpl.fire(AfterDeploymentValidationImpl.java:28)
	at org.jboss.weld.bootstrap.WeldStartup.validateBeans(WeldStartup.java:449)
	at org.jboss.weld.bootstrap.WeldBootstrap.validateBeans(WeldBootstrap.java:90)
	at org.jboss.weld.environment.servlet.WeldServletLifecycle.initialize(WeldServletLifecycle.java:238)
	at org.jboss.weld.environment.servlet.Listener.contextInitialized(Listener.java:121)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:800)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:444)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:791)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:294)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.server.Server.start(Server.java:387)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:354)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at io.fabric8.quickstarts.cxfcdi.ApplicationStarter.startServer(ApplicationStarter.java:91)
	at io.fabric8.quickstarts.cxfcdi.ApplicationStarter.main(ApplicationStarter.java:37)
```

The issue is related to the fact that the maven artifact 

```
 <groupId>com.fasterxml.jackson.dataformat</groupId>
 <artifactId>jackson-dataformat-yaml</artifactId>
```

is not packaged within the lib dir of the docker image

![screenshot 2016-06-03 10 30 57](https://cloud.githubusercontent.com/assets/463790/15773275/5ba5cc96-2976-11e6-97a7-6146b67814fa.png)

**Comment by cmoulliard** [comment]
Resolved with PR
