### ISSUE TITLE
failing system test: jboss-fuse-cxf-rest

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/ipaas-quickstarts#1383]
for more details see the [overview of the archetype system tests](https://github.com/fabric8io/ipaas-quickstarts/blob/master/archetype-itests/ReadMe.md)

here's the log:

```
2016-08-08 17:29:52,941 [Thread-85      ] INFO  ExecutionEventLogger           - --- karaf-maven-plugin:4.0.2.redhat-621067:assembly (karaf-assembly) @ jboss-fuse-cxf-rest ---
2016-08-08 17:29:52,946 [Thread-85      ] INFO  AssemblyMojo                   - Using repositories: https://repo.fusesource.com/nexus/content/groups/public@id=fusesource.m2,https://repo.fusesource.com/nexus/content/groups/ea@id=fusesource.ea,https://maven.repository.redhat.com/ga@id=redhat.ga,https://repo.maven.apache.org/maven2@id=central
2016-08-08 17:29:52,951 [Thread-85      ] INFO  AssemblyMojo                   - Creating work directory
2016-08-08 17:29:52,953 [Thread-85      ] INFO  AssemblyMojo                   - Loading kar and features repositories dependencies
2016-08-08 17:29:52,955 [Thread-85      ] INFO  Builder                        - Generating karaf assembly: /workspace/java/ipaas-quickstarts/archetype-itests/target/createdProjects/jboss-fuse-cxf-rest/target/assembly
2016-08-08 17:29:53,123 [Thread-85      ] INFO  Builder                        - Unzipping kars
2016-08-08 17:29:54,568 [pool-8-thread-2] WARN  AetherBasedResolver            - Error resolving artifactorg.jboss.fuse:fuse-karaf-framework:xml:features:6.2.1.redhat-083:Could not find artifact org.jboss.fuse:fuse-karaf-framework:xml:features:6.2.1.redhat-083 in fusesource.m2 (https://repo.fusesource.com/nexus/content/groups/public/)
shaded.org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact org.jboss.fuse:fuse-karaf-framework:xml:features:6.2.1.redhat-083 in fusesource.m2 (https://repo.fusesource.com/nexus/content/groups/public/)
    at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)[pax-url-aether-2.4.1.jar:]
    at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)[pax-url-aether-2.4.1.jar:]
    at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)[pax-url-aether-2.4.1.jar:]
    at shaded.org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:294)[pax-url-aether-2.4.1.jar:]
    at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:573)[pax-url-aether-2.4.1.jar:]
    at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:528)[pax-url-aether-2.4.1.jar:]
    at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:506)[pax-url-aether-2.4.1.jar:]
    at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:481)[pax-url-aether-2.4.1.jar:]
    at org.apache.karaf.features.internal.download.impl.MavenDownloadTask.download(MavenDownloadTask.java:34)[org.apache.karaf.features.core-4.0.2.redhat-621067.jar:]
    at org.apache.karaf.features.internal.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:58)[org.apache.karaf.features.core-4.0.2.redhat-621067.jar:]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_45]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_45]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)[:1.8.0_45]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)[:1.8.0_45]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_45]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_45]
    at java.lang.Thread.run(Thread.java:745)[:1.8.0_45]
```

**Comment by jstrachan** [comment]
actually quite a few jboss-fuse quickstarts fail:

* jboss-fuse-camel-amq
* jboss-fuse-camel-log
* jboss-fuse-camel-rest-sql
* jboss-fuse-cxf-rest

but it looks like its all the same issue of not being able to download the karaf features as shown above

**Comment by jstrachan** [comment]
actually `jboss-fuse-camel-amq` is now fixed; it got the necessary repo profiles added. Just needs adding to the other jboss-fuse quickstarts I think...

**Comment by jstrachan** [comment]
incidentally I think I've fixed up all the jboss-fuse repos so that they have the repos and use a fuse version thats visible in those repos

**Comment by jstrachan** [comment]
it looks like upgrading to the latest/greatest fabric8 fails:
```
[ERROR] Failed to execute goal org.apache.karaf.tooling:karaf-maven-plugin:4.0.5:assembly (karaf-assembly) on project karaf-camel-amq: Unable to build assembly: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=io.fabric8.fabric8-karaf; type=osgi.bundle; version="[2.2.148,2.2.148]"; resolution:=mandatory [caused by: Unable to resolve io.fabric8.fabric8-karaf/2.2.148: missing requirement [io.fabric8.fabric8-karaf/2.2.148] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.apache.commons.codec.binary)(version>=1.10.0)(!(version>=2.0.0)))"] -> [Help 1]
[ERROR] 
```

**Comment by jstrachan** [comment]
BTW you can see the failure in the PR: https://github.com/fabric8-quickstarts/jboss-fuse-camel-amq/pull/6

**Comment by jstrachan** [comment]
seems related to this dependency: https://github.com/fabric8-quickstarts/jboss-fuse-camel-amq/blob/master/pom.xml#L93-L98

**Comment by jstrachan** [comment]
BTW this is the failing pod message on most of the `jboss-fuse-*` quickstarts right now:
```
Checking for *.tar.gz in /deployments
Missing or more than one assembly archive file *.tar.gz in /deployments
```
looks like the fabric8-maven-plugin's docker configuration isn't quite right?

**Comment by astefanutti** [comment]
The `karaf-maven-plugin` configuration must probably be changed from:

    <archiveTarGz>false</archiveTarGz>

To something like:

    <archiveTarGz>true</archiveTarGz>
    <archiveZip>false</archiveZip>

**Comment by jstrachan** [comment]
@astefanutti do you fancy trying it out and submitting a pull request? :)

**Comment by astefanutti** [comment]
@jstrachan we're on it 😄:
* `jboss-fuse-camel-amq`: should be ok thanks to @lburgazzoli 
* `jboss-fuse-camel-rest-sql`: fabric8-quickstarts/jboss-fuse-camel-rest-sql#6 (but it looks like I'm not whitelisted in the CI job 😢)
* `jboss-fuse-camel-log`: should be updated by @lburgazzoli soon
* `jboss-fuse-cxf-rest`: I'll take care of it ASAP

**Comment by jstrachan** [comment]
@astefanutti awesome thanks!

**Comment by lburgazzoli** [comment]
@jstrachan to get all the fuse/karaf quickstart fixed a new relase of kubernetes-client and fabric8 is required as I've fixed some issues related to different karaf version used upstream and in fuse

**Comment by dhirajsb** [comment]
Closing stale issue
