### ISSUE TITLE
fabric8-forge release failing: Could not find artifact org.jboss.teiid:teiid-runtime:jar:9.0.0.Final in jboss-public-repository-group 

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/ipaas-quickstarts#1425]
Another quickstart breaking the release.
 
https://ci.fabric8.io/job/fabric8-forge-pullreq/738/console
```
[ERROR] Failed to execute goal on project my-spring-boot-camel-teiid: Could not resolve dependencies for project org.example:my-spring-boot-camel-teiid:jar:1.0.0-SNAPSHOT: The following artifacts could not be resolved: org.jboss.teiid:teiid-runtime:jar:9.0.0.Final, org.jboss.teiid.connectors:translator-jdbc:jar:9.0.0.Final: Could not find artifact org.jboss.teiid:teiid-runtime:jar:9.0.0.Final in jboss-public-repository-group (https://repository.jboss.org/nexus/content/groups/public/) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
Sep 26, 2016 3:44:47 PM io.fabric8.forge.systest.ProjectGenerator runMavenGoals
INFO: maven result 1 exception: null
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 302.292 sec <<< FAILURE! - in io.fabric8.forge.systest.PopulateMavenRepositoryTest
testPopulateMavenRepo(io.fabric8.forge.systest.PopulateMavenRepositoryTest)  Time elapsed: 302.19 sec  <<< FAILURE!
java.lang.AssertionError: Failed to invoke maven goals: [package] in folder: /mnt/hudson_workspace/workspace/fabric8-forge-pullreq/fabric8-forge/target/createdProjects/spring-boot-camel-teiid-archetype/my-spring-boot-camel-teiid. Exit Code:  expected:<0> but was:<1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at io.fabric8.forge.systest.ProjectGenerator.runMavenGoals(ProjectGenerator.java:320)
	at io.fabric8.forge.systest.ProjectGenerator.useProjectFromArchetype(ProjectGenerator.java:260)
	at io.fabric8.forge.systest.ProjectGenerator.createProjectFromArchetype(ProjectGenerator.java:219)
	at io.fabric8.forge.systest.PopulateMavenRepositoryTest.createProjects(PopulateMavenRepositoryTest.java:90)
```

**Comment by rawlingsj** [comment]
I'll try disabling the `spring-boot-camel-teiid` quickstart and release again.

**Comment by rawlingsj** [comment]
PR to disable archetype here https://github.com/fabric8io/ipaas-quickstarts/pull/1426
