### ISSUE TITLE
Quickstarts failing under 4.0.152

### ISSUE THREAD

**Issue by tdcox** [fabric8io/ipaas-quickstarts#1515]
Looks like there is an issue with quickstarts failing to fully build under 4.0.152 on GKE.

I get the following problem with the default Vert.x QS and the Spring Boot one:

The code compiles and the unit tests pass. Then before the fabric8:push, I see

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:09 min
[INFO] Finished at: 2017-09-11T16:59:20+00:00
[INFO] Final Memory: 48M/537M
[INFO] ------------------------------------------------------------------------
[Pipeline] findFiles
[Pipeline] junit
Recording test results
[Pipeline] findFiles
[Pipeline] echo
Looking for matching Build null
[Pipeline] echo
Failed to find buildName due to: java.lang.IllegalArgumentException: Name must be provided.
[Pipeline] echo
Checking sonarqube exists
[Pipeline] echo
Code validation service: sonarqube not available
[Pipeline] echo
s2i mode: false
[Pipeline] retry
[Pipeline] {
[Pipeline] sh
[tdcox_demo05t01_master-N2C2CLYCYRWQZRUKSF7YN2BAZR4DGO6J4YF5FH3KEBSL7JQP3GBQ] Running shell script
+ mvn fabric8:push -Ddocker.push.registry=

This then leads to:

[INFO] F8> Running generator vertx
[INFO] F8> vertx: Using Docker image registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift as base / builder
[ERROR] F8> Cannot temporarily tag booster/booster-rest-http-vertx:1.0.1 with /booster/booster-rest-http-vertx:1.0.1 because target image already exists. Please remove this and retry.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.656 s
[INFO] Finished at: 2017-09-11T16:59:37+00:00
[INFO] Final Memory: 39M/308M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.5.22:push (default-cli) on project booster-rest-http-vertx: Cannot temporarily tag booster/booster-rest-http-vertx:1.0.1 with /booster/booster-rest-http-vertx:1.0.1 because target image already exists. Please remove this and retry. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[Pipeline] }
ERROR: script returned exit code 1

_Same error for both quickstarts.
Full log here:_

https://gist.github.com/tdcox/61ab56709b5c65cd63b5e567eb035ebc

**Comment by rawlingsj** [comment]
Thanks @tdcox I think I know what this is and I'm currently working on a better approach so hopefully have this fixed tomorrow.

**Comment by rawlingsj** [comment]
We just added support for deploying fabric8 4.x on GKE with http, this means we can avoid using https when we don't auto generate signed certs for ingress rules.  We can also now push to the internal docker registry from tenant pipelines without having to manually update each cluster node and add insecure registry DOCKER_OPTS.

I just tested using the latest gofabric8 and fabric8 4.x by running this..
```
gofabric8 deploy --namespace fabric8 --http=true --package=system --legacy=false -y
```
Hopefully that will avoid the error reported here too, if not it should be a simple fix now.

**Comment by tdcox** [comment]
Sorry, perhaps I should have been clearer. I am deployed using a real domain and with certificates enabled. Https access across the internet has been working.

f8tentant fails to restart with:

{"level":"info","msg":"Configured connection pool max idle 90","time":"2017-09-12 21:09:55"}
{"level":"info","msg":"Configured connection pool max open 90","time":"2017-09-12 21:09:55"}
{"current_version":2,"level":"info","msg":"Current version 2. Nothing to update.","next_version":3,"pkg":"github.com/fabric8-services/fabric8-tenant/migration","time":"2017-09-12 21:09:55"}
{"err":"Unknown response:\n\u003chtml\u003e\r\n\u003chead\u003e\u003ctitle\u003e503 Service Temporarily Unavailable\u003c/title\u003e\u003c/head\u003e\r\n\u003cbody bgcolor=\"white\"\u003e\r\n\u003ccenter\u003e\u003ch1\u003e503 Service Temporarily Unavailable\u003c/h1\u003e\u003c/center\u003e\r\n\u003chr\u003e\u003ccenter\u003enginx/1.13.3\u003c/center\u003e\r\n\u003c/body\u003e\r\n\u003c/html\u003e\r\n\nGET /auth/realms/fabric8 HTTP/1.1\r\nHost: keycloak.fabric.f8.kill-9.co.uk\r\nAccept: application/json\r\n\r\n","level":"panic","msg":"failed to parse public token","pid":1,"time":"2017-09-12 21:09:55"}
panic: (*logrus.Entry) (0xa28dc0,0xc4203d80f0)
 goroutine 1 [running]:
github.com/fabric8-services/fabric8-tenant/vendor/github.com/Sirupsen/logrus.Entry.log(0xc420016410, 0xc4201b8600, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x40e600, ...)
	/home/jenkins/go/src/github.com/fabric8-services/fabric8-tenant/vendor/github.com/Sirupsen/logrus/entry.go:124 +0x340
github.com/fabric8-services/fabric8-tenant/vendor/github.com/Sirupsen/logrus.(*Entry).Panic(0xc4203d80a0, 0xc42049f750, 0x1, 0x1)
	/home/jenkins/go/src/github.com/fabric8-services/fabric8-tenant/vendor/github.com/Sirupsen/logrus/entry.go:169 +0x11b
github.com/fabric8-services/fabric8-tenant/vendor/github.com/Sirupsen/logrus.(*Entry).Panicln(0xc4203d80a0, 0xc42049f7c8, 0x1, 0x1)
	/home/jenkins/go/src/github.com/fabric8-services/fabric8-tenant/vendor/github.com/Sirupsen/logrus/entry.go:264 +0xe0
github.com/fabric8-services/fabric8-tenant/vendor/github.com/fabric8-services/fabric8-wit/log.Panic(0x0, 0x0, 0xc4201b83f0, 0xa4f78f, 0x1c, 0x0, 0x0, 0x0)
	/home/jenkins/go/src/github.com/fabric8-services/fabric8-tenant/vendor/github.com/fabric8-services/fabric8-wit/log/log.go:248 +0x24f
main.main()
	/home/jenkins/go/src/github.com/fabric8-services/fabric8-tenant/main.go:134 +0x2070

Keycloak shows:

Readiness probe failed: Get http://10.60.1.49:8080/auth: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
Back-off restarting failed container
Error syncing pod
