### ISSUE TITLE
docker-build of karaf quickstarts fails

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/ipaas-quickstarts#747]
in the karaf camel-log it fails with some error. Just logged a ticket to not forget

**Comment by davsclaus** [comment]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:12 min
[INFO] Finished at: 2015-10-01T11:27:55+02:00
[INFO] Final Memory: 143M/864M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.jolokia:docker-maven-plugin:0.13.3:build (default) on project quickstart-karaf-camel-log: Failed to create assembly for docker image: Error creating assembly archive docker: Failed to read filesystem attributes for: /Users/davsclaus/workspace/quickstarts/quickstart/karaf/camel-log/target/quickstart-karaf-camel-log-2.2.38-SNAPSHOT.tar.gz with mode dir -> [Help 1]

**Comment by davsclaus** [comment]
[ERROR] Failed to execute goal org.jolokia:docker-maven-plugin:0.13.3:build (default) on project quickstart-karaf-camel-rest-sql: Failed to create assembly for docker image: Error creating assembly archive docker: Failed to read filesystem attributes for: /Users/davsclaus/workspace/quickstarts/quickstart/karaf/camel-rest-sql/target/quickstart-karaf-camel-rest-sql-2.2.38-SNAPSHOT.tar.gz with mode dir -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.jolokia:docker-maven-plugin:0.13.3:build (default) on project quickstart-karaf-camel-rest-sql: Failed to create assembly for docker image: Error creating assembly archive docker: Failed to read filesystem attributes for: /Users/davsclaus/workspace/quickstarts/quickstart/karaf/camel-rest-sql/target/quickstart-karaf-camel-rest-sql-2.2.38-SNAPSHOT.tar.gz with mode dir
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to create assembly for docker image: Error creating assembly archive docker: Failed to read filesystem attributes for: /Users/davsclaus/workspace/quickstarts/quickstart/karaf/camel-rest-sql/target/quickstart-karaf-camel-rest-sql-2.2.38-SNAPSHOT.tar.gz with mode dir
	at org.jolokia.docker.maven.assembly.DockerAssemblyManager.createAssemblyArchive(DockerAssemblyManager.java:225)
	at org.jolokia.docker.maven.assembly.DockerAssemblyManager.createDockerTarArchive(DockerAssemblyManager.java:70)
	at org.jolokia.docker.maven.service.BuildService.createArchive(BuildService.java:82)
	at org.jolokia.docker.maven.service.BuildService.buildImage(BuildService.java:76)
	at org.jolokia.docker.maven.service.BuildService.buildImage(BuildService.java:54)
	at org.jolokia.docker.maven.AbstractBuildSupportMojo.buildImage(AbstractBuildSupportMojo.java:60)
	at org.jolokia.docker.maven.BuildMojo.buildImage(BuildMojo.java:47)
	at org.jolokia.docker.maven.BuildMojo.executeInternal(BuildMojo.java:37)
	at org.jolokia.docker.maven.AbstractDockerMojo.execute(AbstractDockerMojo.java:174)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: org.apache.maven.plugin.assembly.archive.ArchiveCreationException: Error creating assembly archive docker: Failed to read filesystem attributes for: /Users/davsclaus/workspace/quickstarts/quickstart/karaf/camel-rest-sql/target/quickstart-karaf-camel-rest-sql-2.2.38-SNAPSHOT.tar.gz
	at org.apache.maven.plugin.assembly.archive.DefaultAssemblyArchiver.createArchive(DefaultAssemblyArchiver.java:169)
	at org.jolokia.docker.maven.assembly.DockerAssemblyManager.createAssemblyArchive(DockerAssemblyManager.java:223)
	... 29 more
Caused by: org.codehaus.plexus.archiver.ArchiverException: Failed to read filesystem attributes for: /Users/davsclaus/workspace/quickstarts/quickstart/karaf/camel-rest-sql/target/quickstart-karaf-camel-rest-sql-2.2.38-SNAPSHOT.tar.gz
	at org.codehaus.plexus.archiver.util.ArchiverAttributeUtils.getFileAttributes(ArchiverAttributeUtils.java:30)
	at org.apache.maven.plugin.assembly.archive.phase.FileItemAssemblyPhase.execute(FileItemAssemblyPhase.java:117)
	at org.apache.maven.plugin.assembly.archive.DefaultAssemblyArchiver.createArchive(DefaultAssemblyArchiver.java:162)
	... 30 more
Caused by: java.nio.file.NoSuchFileException: /Users/davsclaus/workspace/quickstarts/quickstart/karaf/camel-rest-sql/target/quickstart-karaf-camel-rest-sql-2.2.38-SNAPSHOT.tar.gz
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileAttributeViews$Posix.readAttributes(UnixFileAttributeViews.java:208)
	at sun.nio.fs.UnixFileAttributeViews$Posix.readAttributes(UnixFileAttributeViews.java:121)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
	at java.nio.file.Files.readAttributes(Files.java:1684)
	at org.codehaus.plexus.components.io.attributes.Java7AttributeUtils.getFileAttributes(Java7AttributeUtils.java:124)
	at org.codehaus.plexus.components.io.attributes.Java7FileAttributes.<init>(Java7FileAttributes.java:62)
	at org.codehaus.plexus.components.io.attributes.PlexusIoResourceAttributeUtils.getFileAttributesByPathJava7(PlexusIoResourceAttributeUtils.java:335)
	at org.codehaus.plexus.components.io.attributes.PlexusIoResourceAttributeUtils.getFileAttributesByPath(PlexusIoResourceAttributeUtils.java:197)
	at org.codehaus.plexus.components.io.attributes.PlexusIoResourceAttributeUtils.getFileAttributes(PlexusIoResourceAttributeUtils.java:174)
	at org.codehaus.plexus.archiver.util.ArchiverAttributeUtils.getFileAttributes(ArchiverAttributeUtils.java:28)
	... 32 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by davsclaus** [comment]
Its as if the .tar.gz is not generated
```
Caused by: java.nio.file.NoSuchFileException: /Users/davsclaus/workspace/quickstarts/quickstart/karaf/camel-rest-sql/target/quickstart-karaf-camel-rest-sql-2.2.38-SNAPSHOT.tar.gz
```

And in that directory I have
```
davsclaus:~/workspace/quickstarts (master)/$ ls /Users/davsclaus/workspace/quickstarts/quickstart/karaf/camel-rest-sql/target/
classes/                             docker/                              fabric8/                             generated-sources/                   quickstart-karaf-camel-rest-sql.jar
```

notice there is no .tar.gz file

**Comment by rhuss** [comment]
That's an issue with the profile and configuration merging.

When you use `mvn clean install docker:build` it works.

I will fix the profile.

**Comment by davsclaus** [comment]
@rhuss what was the decision on the profiles? Do we need those maven profiles anymore for docker-push / docker-pull and so on? If not this will reduce and make the pom.xml much easier to maintain and understand.

**Comment by davsclaus** [comment]
@rawlingsj see ^^^ do you use the maven profiles when you do a release? eg such as these
https://github.com/fabric8io/ipaas-quickstarts/blob/master/quickstart/war/camel-servlet/pom.xml#L176

**Comment by rhuss** [comment]
@davsclaus I removed the profiles within my branch already which I want to push as soon as the the hawt-app-plugin has been released with the latest changes.

**Comment by rhuss** [comment]
In fact, we git rid now of all profiles in the quickstarts ....

**Comment by davsclaus** [comment]
yay sounds good, then this should be fixed

**Comment by rawlingsj** [comment]
@davsclaus no only the release profile is used in the release https://github.com/fabric8io/ipaas-quickstarts/blob/master/pom.xml#L293

**Comment by rawlingsj** [comment]
so removing those docker-push and docker-pull profiles would be great

**Comment by rhuss** [comment]
Ok, will merge ASAP (when I could test with the new hawt-app-plugin + I will need to release a new d-m-p, too)

**Comment by davsclaus** [comment]
upgraded so we should be good now
