### ISSUE TITLE
The kubernetes integration tests dont work on the quickstarts

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/ipaas-quickstarts#761]
Running

```
mvn clean install -Pts.kube`
```

in the `quickstart` directory fails with

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running io.fabric8.tests.integration.KubernetesIntegrationKT
Initializing Session:a102c335-d921-489c-ae93-73a3a046ebac
Using Kubernetes at: https://kubernetes.default.svc/
Creating kubernetes resources inside namespace: itest-a102c335-d921-489c-ae93-73a3a046ebac
if you use OpenShift then type this switch namespaces:     oc project itest-a102c335-d921-489c-ae93-73a3a046ebac
if you use kubernetes then type this to switch namespaces: kubectl namespace itest-a102c335-d921-489c-ae93-73a3a046ebac
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.842 sec <<< FAILURE! - in io.fabric8.tests.integration.KubernetesIntegrationKT
io.fabric8.tests.integration.KubernetesIntegrationKT  Time elapsed: 1.841 sec  <<< ERROR!
io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.create(BaseOperation.java:215)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation$1.visit(BaseOperation.java:225)
	at io.fabric8.kubernetes.api.model.DoneableNamespace.done(DoneableNamespace.java:17)
	at io.fabric8.arquillian.kubernetes.SessionListener.createNamespace(SessionListener.java:216)
	at io.fabric8.arquillian.kubernetes.SessionListener.start(SessionListener.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:145)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:116)
	at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:67)
	at io.fabric8.arquillian.kubernetes.SuiteListener.start(SuiteListener.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
	at org.jboss.arquillian.test.impl.TestContextHandler.createSuiteContext(TestContextHandler.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:145)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:116)
	at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.beforeSuite(EventTestRunnerAdaptor.java:75)
	at org.jboss.arquillian.junit.Arquillian.run(Arquillian.java:115)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.util.concurrent.ExecutionException: java.net.UnknownHostException: kubernetes.default.svc: nodename nor servname provided, or not known
	at io.fabric8.kubernetes.client.internal.com.ning.http.client.providers.netty.future.NettyResponseFuture.abort(NettyResponseFuture.java:231)
	at io.fabric8.kubernetes.client.internal.com.ning.http.client.providers.netty.request.NettyRequestSender.abort(NettyRequestSender.java:420)
	at io.fabric8.kubernetes.client.internal.com.ning.http.client.providers.netty.request.NettyRequestSender.sendRequestWithNewChannel(NettyRequestSender.java:288)
	at io.fabric8.kubernetes.client.internal.com.ning.http.client.providers.netty.request.NettyRequestSender.sendRequestWithCertainForceConnect(NettyRequestSender.java:140)
	at io.fabric8.kubernetes.client.internal.com.ning.http.client.providers.netty.request.NettyRequestSender.sendRequest(NettyRequestSender.java:115)
	at io.fabric8.kubernetes.client.internal.com.ning.http.client.providers.netty.NettyAsyncHttpProvider.execute(NettyAsyncHttpProvider.java:87)
	at io.fabric8.kubernetes.client.internal.com.ning.http.client.AsyncHttpClient.executeRequest(AsyncHttpClient.java:517)
	at io.fabric8.kubernetes.client.internal.com.ning.http.client.AsyncHttpClient$BoundRequestBuilder.execute(AsyncHttpClient.java:229)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handleResponse(BaseOperation.java:504)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handleCreate(BaseOperation.java:520)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.create(BaseOperation.java:208)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation$1.visit(BaseOperation.java:225)
	at io.fabric8.kubernetes.api.model.DoneableNamespace.done(DoneableNamespace.java:17)
	at io.fabric8.arquillian.kubernetes.SessionListener.createNamespace(SessionListener.java:216)
	at io.fabric8.arquillian.kubernetes.SessionListener.start(SessionListener.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:145)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:116)
	at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:67)
	at io.fabric8.arquillian.kubernetes.SuiteListener.start(SuiteListener.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
	at org.jboss.arquillian.test.impl.TestContextHandler.createSuiteContext(TestContextHandler.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:145)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:116)
	at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.beforeSuite(EventTestRunnerAdaptor.java:75)
	at org.jboss.arquillian.junit.Arquillian.run(Arquillian.java:115)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.net.UnknownHostException: kubernetes.default.svc: nodename nor servname provided, or not known
```

**Comment by davsclaus** [comment]
I have my .kube/config as

```
davsclaus:~/$ cat .kube/config
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://172.28.128.4:8443
  name: 172-28-128-4:8443
contexts:
- context:
    cluster: 172-28-128-4:8443
    namespace: default
    user: admin/172-28-128-4:8443
  name: default/172-28-128-4:8443/admin
current-context: default/172-28-128-4:8443/admin
kind: Config
preferences: {}
users:
- name: admin/172-28-128-4:8443
  user:
    token: r2RNegkGzzNFLlzdvd0aU0NG9YQRM7iw0lW-JYrmxDU
davsclaus:~/$
```

And no `KUBERNETES_MASTER` env

**Comment by davsclaus** [comment]
Ah need the KUBERNETES_MASTER env.

**Comment by davsclaus** [comment]
Now when the test runs I get docker pull errors
```
No pods are available yet, waiting...
Waiting for container:quickstart-java-camel-spring. Reason:image pull failed for docker.io/fabric8/quickstart-java-camel-spring:2.2.42-SNAPSHOT, this may be because there are no credentials on this request.  details: (Error while pulling image: Get https://index.docker.io/v1/repositories/fabric8/quickstart-java-camel-spring/images: dial tcp: lookup index.docker.io: no such host)
Waiting for container:quickstart-java-camel-spring. Reason:image pull failed for docker.io/fabric8/quickstart-java-camel-spring:2.2.42-SNAPSHOT, this may be because there are no credentials on this request.  details: (Error while pulling image: Get https://index.docker.io/v1/repositories/fabric8/quickstart-java-camel-spring/images: dial tcp: lookup index.docker.io: no such host)
Waiting for container:quickstart-java-camel-spring. Reason:image pull failed for docker.io/fabric8/quickstart-java-camel-spring:2.2.42-SNAPSHOT, this may be because there are no credentials on this request.  details: (Error while pulling image: Get https://index.docker.io/v1/repositories/fabric8/quickstart-java-camel-spring/images: dial tcp: lookup index.docker.io: no such host)
Waiting for container:quickstart-java-camel-spring. Reason:image pull failed for docker.io/fabric8/quickstart-java-camel-spring:2.2.42-SNAPSHOT, this may be because there are no credentials on this request.  details: (Error while pulling image: Get https://index.docker.io/v1/repositories/fabric8/quickstart-java-camel-spring/images: dial tcp: lookup index.docker.io: no such host)
Waiting for container:quickstart-java-camel-spring. Reason:image pull failed for docker.io/fabric8/quickstart-java-camel-spring:2.2.42-SNAPSHOT, this may be because there are no credentials on this request.  details: (Error while pulling image: Get https://index.docker.io/v1/repositories/fabric8/quickstart-java-camel-spring/images: dial tcp: lookup index.docker.io: no such host)
Waiting for container:quickstart-java-camel-spring. Reason:image pull failed for docker.io/fabric8/quickstart-java-camel-spring:2.2.42-SNAPSHOT, this may be because there are no credentials on this request.  details: (Error while pulling image: Get https://index.docker.io/v1/repositories/fabric8/quickstart-java-camel-spring/images: dial tcp: lookup index.docker.io: no such host)
Waiting for container:quickstart-java-camel-spring. Reason:image pull failed for docker.io/fabric8/quickstart-java-camel-spring:2.2.42-SNAPSHOT, this may be because there are no credentials on this request.  details: (Error while pulling image: Get https://index.docker.io/v1/repositories/fabric8/quickstart-java-camel-spring/images: dial tcp: lookup index.docker.io: no such host)
Waiting for container:quickstart-java-camel-spring. Reason:image pull failed for docker.io/fabric8/quickstart-java-camel-spring:2.2.42-SNAPSHOT, this may be because there are no credentials on this request.  details: (Error while pulling image: Get https://index.docker.io/v1/repositories/fabric8/quickstart-java-camel-spring/images: dial tcp: lookup index.docker.io: no such host)
Waiting for container:quickstart-java-camel-spring. Reason:image pull failed for docker.io/fabric8/quickstart-java-camel-spring:2.2.42-SNAPSHOT, this may be because there are no credentials on this request.  details: (Error while pulling image: Get https://index.docker.io/v1/repositories/fabric8/quickstart-java-camel-spring/images: dial tcp: lookup index.docker.io: no such host)
```

**Comment by davsclaus** [comment]
iocanis fixed his in next fabric8 release so it reads from the kube config
