### ISSUE TITLE
quickstart - camel CDI HTTP example can't call HTTP Server

### ISSUE THREAD

**Issue by cmoulliard** [fabric8io/ipaas-quickstarts#863]
This error is generated when the Camel CDI HTTP Quickstart is deployed as pod in openshift 

```
Exchange
---------------------------------------------------------------------------------------------------------------------------------------
Exchange[
	Id                  ID-demo1-c4da89531d6d1faf0ddc8e85ca3a64c9-wfl32-57134-1445451609524-0-74
	ExchangePattern     InOnly
	Headers             {breadcrumbId=ID-demo1-c4da89531d6d1faf0ddc8e85ca3a64c9-wfl32-57134-1445451609524-0-73, CamelHttpUrl=http://localhost:8080/camel/hello, CamelRedelivered=false, CamelRedeliveryCounter=0, firedTime=Wed Oct 21 18:23:11 UTC 2015, name=Camel37}
	BodyType            null
	Body                [Body is null]
]

Stacktrace
---------------------------------------------------------------------------------------------------------------------------------------
java.net.ConnectException: Cannot connect to localhost:8080
	at org.apache.camel.component.netty4.NettyProducer.openChannel(NettyProducer.java:436)
	at org.apache.camel.component.netty4.NettyProducer$NettyProducerPoolableObjectFactory.makeObject(NettyProducer.java:504)
	at org.apache.camel.component.netty4.NettyProducer$NettyProducerPoolableObjectFactory.makeObject(NettyProducer.java:499)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1188)
	at org.apache.camel.component.netty4.NettyProducer.process(NettyProducer.java:204)
	at org.apache.camel.component.netty4.http.NettyHttpProducer.process(NettyHttpProducer.java:52)
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:141)
	at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:77)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:460)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:190)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:121)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:83)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:190)
	at org.apache.camel.component.timer.TimerConsumer.sendTimerExchange(TimerConsumer.java:165)
	at org.apache.camel.component.timer.TimerConsumer$1.run(TimerConsumer.java:73)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: java.net.ConnectException: Connection refused: localhost/127.0.0.1:8080
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:224)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:289)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at java.lang.Thread.run(Thread.java:745)
2015-10-21 18:23:11,359 [0 - timer://foo] WARN  TimerConsumer                  - Error processing exchange. Exchange[ID-demo1-c4da89531d6d1faf0ddc8e85ca3a64c9-wfl32-57134-1445451
````
As it seems that we need a HTTP Server, which other Camel quickstart can we deploy to get a response ?

**Comment by davsclaus** [comment]
Read the readme please!
