### ISSUE TITLE
karaf quickstart do not log to docker logs

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/ipaas-quickstarts#877]
They only log the initial part of booting up karaf, but any log activity that happens since in the karaf log is not shown.

If you run from docker like
```
davsclaus:~/workspace/quickstarts/quickstart/karaf/camel-log (master)/$ docker run -it fabric8/quickstart-karaf-camellog:2.2.57-SNAPSHOT
```

Then that is all you see
```
Checking for *.tar.gz in /opt/jboss/deploy
Executing /opt/jboss/karaf/bin/karaf server ...
I> No access restrictor found, access to all MBean is allowed
Jolokia: Agent started with URL http://172.17.0.10:8778/jolokia/
2015-10-23 13:19:26,793 | INFO  | FelixStartLevel  | fileinstall                      | 6 - org.apache.felix.fileinstall - 3.5.0 | Creating configuration from profile.cfg
2015-10-23 13:19:26,798 | INFO  | FelixStartLevel  | fileinstall                      | 6 - org.apache.felix.fileinstall - 3.5.0 | Creating configuration from org.apache.karaf.management.cfg
2015-10-23 13:19:26,801 | INFO  | FelixStartLevel  | fileinstall                      | 6 - org.apache.felix.fileinstall - 3.5.0 | Creating configuration from org.apache.karaf.features.repos.cfg
2015-10-23 13:19:26,804 | INFO  | FelixStartLevel  | fileinstall                      | 6 - org.apache.felix.fileinstall - 3.5.0 | Creating configuration from org.ops4j.pax.url.mvn.cfg
2015-10-23 13:19:26,807 | INFO  | FelixStartLevel  | fileinstall                      | 6 - org.apache.felix.fileinstall - 3.5.0 | Creating configuration from org.apache.karaf.jaas.cfg
2015-10-23 13:19:26,817 | INFO  | FelixStartLevel  | fileinstall                      | 6 - org.apache.felix.fileinstall - 3.5.0 | Creating configuration from jmx.acl.cfg
2015-10-23 13:19:26,820 | INFO  | FelixStartLevel  | fileinstall                      | 6 - org.apache.felix.fileinstall - 3.5.0 | Creating configuration from org.apache.karaf.shell.cfg
2015-10-23 13:19:26,899 | INFO  | FelixStartLevel  | BlueprintExtender                | 9 - org.apache.aries.blueprint.core - 1.4.3 | No quiesce support is available, so blueprint components will not participate in quiesce operations
2015-10-23 13:19:27,654 | INFO  | FelixStartLevel  | BlueprintContainerImpl           | 9 - org.apache.aries.blueprint.core - 1.4.3 | Bundle org.apache.karaf.jaas.command is waiting for namespace handlers [http://karaf.apache.org/xmlns/shell/v1.1.0]
2015-10-23 13:19:28,155 | INFO  | FelixStartLevel  | BlueprintContainerImpl           | 9 - org.apache.aries.blueprint.core - 1.4.3 | Bundle org.apache.karaf.shell.commands is waiting for namespace handlers [http://karaf.apache.org/xmlns/shell/v1.0.0]
```

But the application is logging as its the camel-log quickstart that logs every 5th second.

**Comment by davsclaus** [comment]
Okay it looks like the `org.ops4j.pax.logging.cfg` should have out in the loggers so it log to standard out

**Comment by davsclaus** [comment]
It should be
```
log4j.rootLogger=INFO, stdout, out, osgi:*
```

**Comment by jimmidyson** [comment]
Can you make sure it's not logging to file as well? Stdout only otherwise we're wasting disk space & increasing I/O on the node.

**Comment by davsclaus** [comment]
yeah good idea, this is how the others are done.

**Comment by davsclaus** [comment]
At first glance it does not look like this plugin can do that
https://github.com/jboss-fuse/karaf/blob/4.0.x.redhat-6-2-x-patch/tooling/karaf-maven-plugin/src/main/java/org/apache/karaf/tooling/AssemblyMojo.java#L110

So we may need to add yet another maven plugin that copy over the logging file or something.

**Comment by davsclaus** [comment]
Add the resource plugin to overwrite the file seems the way forward for now

**Comment by davsclaus** [comment]
Okay it works for `docker run` but not on openshift

```
davsclaus:~/workspace/quickstarts/quickstart/karaf/camel-log (877)/$ docker run -it fabric8/quickstart-karaf-camellog:2.2.57-SNAPSHOT
Checking for *.tar.gz in /opt/jboss/deploy
Executing /opt/jboss/karaf/bin/karaf server ...
I> No access restrictor found, access to all MBean is allowed
Jolokia: Agent started with URL http://172.17.0.13:8778/jolokia/
2015-10-23 13:46:06,269 | INFO  | FelixStartLevel  | fileinstall                      | 6 - org.apache.felix.fileinstall - 3.5.0 | Creating configuration from org.apache.karaf.management.cfg
2015-10-23 13:46:06,276 | INFO  | FelixStartLevel  | fileinstall                      | 6 - org.apache.felix.fileinstall - 3.5.0 | Creating configuration from org.apache.karaf.features.repos.cfg
2015-10-23 13:46:06,281 | INFO  | FelixStartLevel  | fileinstall                      | 6 - org.apache.felix.fileinstall - 3.5.0 | Creating configuration from org.ops4j.pax.url.mvn.cfg
2015-10-23 13:46:06,292 | INFO  | FelixStartLevel  | fileinstall                      | 6 - org.apache.felix.fileinstall - 3.5.0 | Creating configuration from org.apache.karaf.jaas.cfg
2015-10-23 13:46:06,296 | INFO  | FelixStartLevel  | fileinstall                      | 6 - org.apache.felix.fileinstall - 3.5.0 | Creating configuration from jmx.acl.cfg
2015-10-23 13:46:06,328 | INFO  | FelixStartLevel  | fileinstall                      | 6 - org.apache.felix.fileinstall - 3.5.0 | Creating configuration from org.apache.karaf.shell.cfg
2015-10-23 13:46:06,468 | INFO  | FelixStartLevel  | BlueprintExtender                | 9 - org.apache.aries.blueprint.core - 1.4.3 | No quiesce support is available, so blueprint components will not participate in quiesce operations
2015-10-23 13:46:07,172 | INFO  | FelixStartLevel  | BlueprintContainerImpl           | 9 - org.apache.aries.blueprint.core - 1.4.3 | Bundle org.apache.karaf.jaas.command is waiting for namespace handlers [http://karaf.apache.org/xmlns/shell/v1.1.0]
2015-10-23 13:46:07,681 | INFO  | FelixStartLevel  | BlueprintContainerImpl           | 9 - org.apache.aries.blueprint.core - 1.4.3 | Bundle org.apache.karaf.shell.commands is waiting for namespace handlers [http://karaf.apache.org/xmlns/shell/v1.0.0]
2015-10-23 13:46:08,665 | INFO  | FelixStartLevel  | BlueprintContainerImpl           | 9 - org.apache.aries.blueprint.core - 1.4.3 | Bundle io.fabric8.quickstarts.quickstart-karaf-camel-log is waiting for namespace handlers [http://camel.apache.org/schema/blueprint]
2015-10-23 13:46:08,958 | INFO  | FelixStartLevel  | Activator                        | 32 - org.apache.camel.camel-core - 2.16.0 | Camel activator starting
2015-10-23 13:46:08,978 | INFO  | FelixStartLevel  | Activator                        | 32 - org.apache.camel.camel-core - 2.16.0 | Camel activator started
2015-10-23 13:46:10,906 | INFO  | rint Extender: 1 | BlueprintCamelContext            | 32 - org.apache.camel.camel-core - 2.16.0 | Apache Camel 2.16.0 (CamelContext: log-example-context) is starting
2015-10-23 13:46:10,908 | INFO  | rint Extender: 1 | ManagedManagementStrategy        | 32 - org.apache.camel.camel-core - 2.16.0 | JMX is enabled
2015-10-23 13:46:11,077 | INFO  | rint Extender: 1 | DefaultRuntimeEndpointRegistry   | 32 - org.apache.camel.camel-core - 2.16.0 | Runtime endpoint registry is in extended mode gathering usage statistics of all incoming and outgoing endpoints (cache limit: 1000)
2015-10-23 13:46:11,236 | INFO  | rint Extender: 1 | BlueprintCamelContext            | 32 - org.apache.camel.camel-core - 2.16.0 | AllowUseOriginalMessage is enabled. If access to the original message is not needed, then its recommended to turn this option off as it may improve performance.
2015-10-23 13:46:11,236 | INFO  | rint Extender: 1 | BlueprintCamelContext            | 32 - org.apache.camel.camel-core - 2.16.0 | StreamCaching is not in use. If using streams then its recommended to enable stream caching. See more details at http://camel.apache.org/stream-caching.html
2015-10-23 13:46:11,285 | INFO  | rint Extender: 1 | BlueprintCamelContext            | 32 - org.apache.camel.camel-core - 2.16.0 | Route: log-route started and consuming from: Endpoint[timer://foo?period=5s]
2015-10-23 13:46:11,317 | INFO  | rint Extender: 1 | BlueprintCamelContext            | 32 - org.apache.camel.camel-core - 2.16.0 | Total 1 routes, of which 1 is started.
2015-10-23 13:46:11,323 | INFO  | rint Extender: 1 | BlueprintCamelContext            | 32 - org.apache.camel.camel-core - 2.16.0 | Apache Camel 2.16.0 (CamelContext: log-example-context) started in 0.411 seconds
2015-10-23 13:46:12,354 | INFO  | #0 - timer://foo | log-route                        | 32 - org.apache.camel.camel-core - 2.16.0 | >>> Hello from Camel! :
2015-10-23 13:46:17,321 | INFO  | #0 - timer://foo | log-route                        | 32 - org.apache.camel.camel-core - 2.16.0 | >>> Hello from Camel! :
```

But when I do `oc logs -f xxx` all I see is the starting piece
```
^Cdavsclaus:~/workspace/fabric8-installer/vagrant/openshift (master)/$ oc logs -f quickstart-karaf-camel-log-29znn
Checking for *.tar.gz in /opt/jboss/deploy
Executing /opt/jboss/karaf/bin/karaf server ...
I> No access restrictor found, access to all MBean is allowed
Jolokia: Agent started with URL https://172.17.0.12:8778/jolokia/
2015-10-23 13:45:23,518 | INFO  | FelixStartLevel  | fileinstall                      | 6 - org.apache.felix.fileinstall - 3.5.0 | Creating configuration from org.apache.karaf.management.cfg
2015-10-23 13:45:23,524 | INFO  | FelixStartLevel  | fileinstall                      | 6 - org.apache.felix.fileinstall - 3.5.0 | Creating configuration from org.apache.karaf.features.repos.cfg
2015-10-23 13:45:23,528 | INFO  | FelixStartLevel  | fileinstall                      | 6 - org.apache.felix.fileinstall - 3.5.0 | Creating configuration from org.ops4j.pax.url.mvn.cfg
2015-10-23 13:45:23,538 | INFO  | FelixStartLevel  | fileinstall                      | 6 - org.apache.felix.fileinstall - 3.5.0 | Creating configuration from org.apache.karaf.jaas.cfg
2015-10-23 13:45:23,541 | INFO  | FelixStartLevel  | fileinstall                      | 6 - org.apache.felix.fileinstall - 3.5.0 | Creating configuration from jmx.acl.cfg
2015-10-23 13:45:23,547 | INFO  | FelixStartLevel  | fileinstall                      | 6 - org.apache.felix.fileinstall - 3.5.0 | Creating configuration from org.apache.karaf.shell.cfg
2015-10-23 13:45:23,640 | INFO  | FelixStartLevel  | BlueprintExtender                | 9 - org.apache.aries.blueprint.core - 1.4.3 | No quiesce support is available, so blueprint components will not participate in quiesce operations
2015-10-23 13:45:24,430 | INFO  | FelixStartLevel  | BlueprintContainerImpl           | 9 - org.apache.aries.blueprint.core - 1.4.3 | Bundle org.apache.karaf.jaas.command is waiting for namespace handlers [http://karaf.apache.org/xmlns/shell/v1.1.0]
2015-10-23 13:45:25,159 | INFO  | FelixStartLevel  | BlueprintContainerImpl           | 9 - org.apache.aries.blueprint.core - 1.4.3 | Bundle org.apache.karaf.shell.commands is waiting for namespace handlers [http://karaf.apache.org/xmlns/shell/v1.0.0]
```

**Comment by jimmidyson** [comment]
That's the same docker container? That's a bug in openshift then.

**Comment by davsclaus** [comment]
yeah would have though but i did a oc rsh and noticed the log configuration wasn't changed but the old one.

**Comment by davsclaus** [comment]
Logged this ticket to get it into the karaf-maven-plugin
https://issues.jboss.org/browse/OSFUSE-72

**Comment by rhuss** [comment]
the logging is setup that during startup of karaf (so very late in the process) logging is set to 

```
# Root logger
log4j.rootLogger=INFO, stdout, osgi:*
log4j.throwableRenderer=org.apache.log4j.OsgiThrowableRenderer

# CONSOLE appender not used by default
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d{ISO8601} | %-5.5p | %-16.16t | %-32.32c{1} | %X{bundle.id} - %X{bundle.name} - %X{bundle.version} | %m%n
```

This is done [here](https://github.com/fabric8io-images/s2i/blob/master/karaf/deploy-and-run.sh#L29)

**Comment by rhuss** [comment]
Hmm, still hangs for me.

Here's a thread dump:

````
015-10-23 16:47:13
Full thread dump OpenJDK 64-Bit Server VM (25.51-b03 mixed mode):

"Camel (log-example-context) thread #0 - timer://foo" #312 daemon prio=5 os_prio=0 tid=0x00007fbc9c4a8000 nid=0x183 in Object.wait() [0x00007fbc6fcfd000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.util.TimerThread.mainLoop(Timer.java:552)
	- locked <0x00000000e115f138> (a java.util.TaskQueue)
	at java.util.TimerThread.run(Timer.java:505)

"Timer-18" #166 daemon prio=5 os_prio=0 tid=0x00007fbc98025000 nid=0xf1 in Object.wait() [0x00007fbc6f4f7000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000000e085a0f0> (a java.util.TaskQueue)
	at java.util.TimerThread.mainLoop(Timer.java:552)
	- locked <0x00000000e085a0f0> (a java.util.TaskQueue)
	at java.util.TimerThread.run(Timer.java:505)

"Blueprint Event Dispatcher: 1" #99 daemon prio=5 os_prio=0 tid=0x00007fbc74379800 nid=0xae waiting on condition [0x00007fbc6f8fb000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000e050fff8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1081)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

"Blueprint Extender: 3" #46 daemon prio=5 os_prio=0 tid=0x00007fbc7421e000 nid=0x79 waiting on condition [0x00007fbc6fbfc000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000e0332fb0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

"Blueprint Extender: 2" #40 daemon prio=5 os_prio=0 tid=0x00007fbc74202800 nid=0x73 waiting on condition [0x00007fbc9042a000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000e0332fb0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1088)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

"Blueprint Extender: 1" #39 daemon prio=5 os_prio=0 tid=0x00007fbc741f4000 nid=0x72 waiting on condition [0x00007fbc90329000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000e0332fb0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1088)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

"fileinstall-/opt/jboss/karaf/etc" #31 daemon prio=5 os_prio=0 tid=0x00007fbc7414e800 nid=0x6b in Object.wait() [0x00007fbc9062c000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:314)
	- locked <0x00000000e0698f78> (a org.apache.felix.fileinstall.internal.DirectoryWatcher)

"Thread-4" #32 daemon prio=5 os_prio=0 tid=0x00007fbc74152000 nid=0x6a runnable [0x00007fbc9052b000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.fs.LinuxWatchService.poll(Native Method)
	at sun.nio.fs.LinuxWatchService.access$600(LinuxWatchService.java:47)
	at sun.nio.fs.LinuxWatchService$Poller.run(LinuxWatchService.java:314)
	at java.lang.Thread.run(Thread.java:745)

"CM Event Dispatcher" #28 daemon prio=5 os_prio=0 tid=0x00007fbc7413e800 nid=0x67 in Object.wait() [0x00007fbc90b32000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000000e06882b0> (a java.util.LinkedList)
	at java.lang.Object.wait(Object.java:502)
	at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:77)
	- locked <0x00000000e06882b0> (a java.util.LinkedList)
	at java.lang.Thread.run(Thread.java:745)

"CM Configuration Updater" #27 daemon prio=5 os_prio=0 tid=0x00007fbc74137000 nid=0x66 in Object.wait() [0x00007fbc90c33000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:77)
	- locked <0x00000000e0688cb8> (a java.util.LinkedList)
	at java.lang.Thread.run(Thread.java:745)

"Karaf Shutdown Socket Thread" #20 daemon prio=5 os_prio=0 tid=0x00007fbc70001800 nid=0x5f runnable [0x00007fbc90d34000]
   java.lang.Thread.State: RUNNABLE
	at java.net.PlainSocketImpl.socketAccept(Native Method)
	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:404)
	at java.net.ServerSocket.implAccept(ServerSocket.java:545)
	at java.net.ServerSocket.accept(ServerSocket.java:513)
	at org.apache.karaf.main.ShutdownSocketThread.run(ShutdownSocketThread.java:57)

"Karaf Lock Monitor Thread" #19 prio=5 os_prio=0 tid=0x00007fbcbc6bb800 nid=0x5e waiting on condition [0x00007fbc90e35000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at org.apache.karaf.main.Main.doMonitor(Main.java:349)
	at org.apache.karaf.main.Main.access$100(Main.java:73)
	at org.apache.karaf.main.Main$1.run(Main.java:325)

"FelixStartLevel" #18 daemon prio=5 os_prio=0 tid=0x00007fbcbc4ee800 nid=0x5d in Object.wait() [0x00007fbc90ffd000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000000e03cb090> (a java.util.ArrayList)
	at java.lang.Object.wait(Object.java:502)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:283)
	- locked <0x00000000e03cb090> (a java.util.ArrayList)
	at java.lang.Thread.run(Thread.java:745)

"FelixFrameworkWiring" #17 daemon prio=5 os_prio=0 tid=0x00007fbcbc4e9000 nid=0x5c in Object.wait() [0x00007fbca8170000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000000e0266490> (a java.util.ArrayList)
	at java.lang.Object.wait(Object.java:502)
	at org.apache.felix.framework.FrameworkWiringImpl.run(FrameworkWiringImpl.java:172)
	- locked <0x00000000e0266490> (a java.util.ArrayList)
	at java.lang.Thread.run(Thread.java:745)

"FelixDispatchQueue" #14 prio=5 os_prio=0 tid=0x00007fbcbc4be800 nid=0x59 in Object.wait() [0x00007fbca8271000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000000e02e39e0> (a java.util.ArrayList)
	at java.lang.Object.wait(Object.java:502)
	at org.apache.felix.framework.util.EventDispatcher.run(EventDispatcher.java:1118)
	- locked <0x00000000e02e39e0> (a java.util.ArrayList)
	at org.apache.felix.framework.util.EventDispatcher.access$000(EventDispatcher.java:55)
	at org.apache.felix.framework.util.EventDispatcher$1.run(EventDispatcher.java:102)
	at java.lang.Thread.run(Thread.java:745)

"RMI TCP Accept-0" #13 daemon prio=5 os_prio=0 tid=0x00007fbcbc3ff000 nid=0x57 runnable [0x00007fbca8673000]
   java.lang.Thread.State: RUNNABLE
	at java.net.PlainSocketImpl.socketAccept(Native Method)
	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:404)
	at java.net.ServerSocket.implAccept(ServerSocket.java:545)
	at java.net.ServerSocket.accept(ServerSocket.java:513)
	at sun.management.jmxremote.LocalRMIServerSocketFactory$1.accept(LocalRMIServerSocketFactory.java:52)
	at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.executeAcceptLoop(TCPTransport.java:400)
	at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.run(TCPTransport.java:372)
	at java.lang.Thread.run(Thread.java:745)

"Service Thread" #12 daemon prio=9 os_prio=0 tid=0x00007fbcbc359000 nid=0x56 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread1" #11 daemon prio=9 os_prio=0 tid=0x00007fbcbc350000 nid=0x55 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Thread-3" #10 prio=5 os_prio=0 tid=0x00007fbc80001000 nid=0x54 runnable [0x00007fbca8a75000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x00000000e03a5b80> (a sun.nio.ch.Util$2)
	- locked <0x00000000e03a5b70> (a java.util.Collections$UnmodifiableSet)
	- locked <0x00000000e03a59c8> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:352)
	at java.lang.Thread.run(Thread.java:745)

"C2 CompilerThread0" #9 daemon prio=9 os_prio=0 tid=0x00007fbcbc34f000 nid=0x53 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Jolokia Agent Cleanup Thread" #8 daemon prio=5 os_prio=0 tid=0x00007fbcbc357800 nid=0x52 in Object.wait() [0x00007fbca8c77000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000000e0191fb0> (a java.lang.Thread)
	at java.lang.Thread.join(Thread.java:1245)
	- locked <0x00000000e0191fb0> (a java.lang.Thread)
	at java.lang.Thread.join(Thread.java:1319)
	at org.jolokia.jvmagent.CleanupThread.joinThreads(CleanupThread.java:110)
	at org.jolokia.jvmagent.CleanupThread.run(CleanupThread.java:60)

"server-timer" #6 daemon prio=5 os_prio=0 tid=0x00007fbcbc22e000 nid=0x50 in Object.wait() [0x00007fbca8e79000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.util.TimerThread.mainLoop(Timer.java:552)
	- locked <0x00000000e03a61b8> (a java.util.TaskQueue)
	at java.util.TimerThread.run(Timer.java:505)

"Signal Dispatcher" #4 daemon prio=9 os_prio=0 tid=0x00007fbcbc13d000 nid=0x4f waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=0 tid=0x00007fbcbc111000 nid=0x4e in Object.wait() [0x00007fbca96b0000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	- locked <0x00000000e021ce30> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

"Reference Handler" #2 daemon prio=10 os_prio=0 tid=0x00007fbcbc10f000 nid=0x4d in Object.wait() [0x00007fbca97b1000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:157)
	- locked <0x00000000e02b1b68> (a java.lang.ref.Reference$Lock)

"main" #1 prio=5 os_prio=0 tid=0x00007fbcbc00b000 nid=0x49 in Object.wait() [0x00007fbcc260e000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000000e015c818> (a org.apache.felix.framework.util.ThreadGate)
	at org.apache.felix.framework.util.ThreadGate.await(ThreadGate.java:79)
	- locked <0x00000000e015c818> (a org.apache.felix.framework.util.ThreadGate)
	at org.apache.felix.framework.Felix.waitForStop(Felix.java:1068)
	at org.apache.karaf.main.Main.awaitShutdown(Main.java:531)
	at org.apache.karaf.main.Main.main(Main.java:185)

"VM Thread" os_prio=0 tid=0x00007fbcbc10a000 nid=0x4c runnable

"GC task thread#0 (ParallelGC)" os_prio=0 tid=0x00007fbcbc020000 nid=0x4a runnable

"GC task thread#1 (ParallelGC)" os_prio=0 tid=0x00007fbcbc022000 nid=0x4b runnable

"VM Periodic Task Thread" os_prio=0 tid=0x00007fbcbc417000 nid=0x58 waiting on condition

JNI global references: 244

Heap
 PSYoungGen      total 173056K, used 37097K [0x00000000f5580000, 0x0000000100000000, 0x0000000100000000)
  eden space 171520K, 21% used [0x00000000f5580000,0x00000000f791dc78,0x00000000ffd00000)
  from space 1536K, 40% used [0x00000000ffe80000,0x00000000fff1c838,0x0000000100000000)
  to   space 1536K, 0% used [0x00000000ffd00000,0x00000000ffd00000,0x00000000ffe80000)
 ParOldGen       total 87552K, used 19669K [0x00000000e0000000, 0x00000000e5580000, 0x00000000f5580000)
  object space 87552K, 22% used [0x00000000e0000000,0x00000000e13354d8,0x00000000e5580000)
 Metaspace       used 33957K, capacity 35812K, committed 36184K, reserved 1081344K
  class space    used 3880K, capacity 4398K, committed 4480K, reserved 1048576K
````

**Comment by rhuss** [comment]
I think it's not a configuration issue but sth is blocking the timer or startup of the context. The configuration looks good and can be easily examined by doing a `oc exec`.
